### ISSUE TITLE
Possible attack vector

### ISSUE THREAD

**Issue by gregology** [nanos/mastodon_get_replies#16]
This is a great script, thanks for sharing it! I just have one concern, the [workflow currently relies on releases from the parent repo](https://github.com/nanos/mastodon_get_replies/blob/main/.github/workflows/get_context.yml#L16). This creates a possible attack vector, if this repo is compromised, all forks may also be compromised. Ideally forked repo workflows would only reference code from within their own repository. The obvious advantage to the current pattern is getting updates for free.

**Comment by nanos** [comment]
Indeed. In the first few versions of this Action, the workflow began with `- uses: actions/checkout@v3` as first step, rather than pulling the latest release in. I have swapped that out a short while ago, to make updating easier.

My thinking is, that if someone is concerned about this, they can change this very simply and easily themselves by just swapping the first step of the workflow with `- uses: actions/checkout@v3`.

**Comment by nanos** [comment]
Should note, though, that I've just discovered this gem:

> Warning: [...] In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days.

[source](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow)

So, I guess users of the GitHub Action do have to do some update at least once every 60 days anyway 🤔

**Comment by nanos** [comment]
> We need a GitHub action that makes changes to the repo every 59 days :trollface:

Pretty much: https://github.com/nanos/mastodon_get_replies/issues/17 😂
