### ISSUE TITLE
Scan lists for accounts and backfill/same for bookmarks

### ISSUE THREAD

**Issue by p37307** [nanos/mastodon_get_replies#19]
**Request 1: Backfill members of lists**

Problem 1. In absence of an AI to figure out what we are interested in, a lot of users use lists to create our very own timeline views of accounts we find important. It can be assumed that many of those accounts on lists are aged in the following list and out of reach of a normal scan.

Desire 1: I propose the script scans lists for members of the list and backfill those accounts, so they are up-to-date.

**Request 2: Backfill Bookmarks**
Problem 2: We bookmark toot posts we are interested in. It would be nice to have those bookmarks up-to-date when we go and look at them.

Desire: Have the script scan and backfill bookmark toot posts.

**Comment by nanos** [comment]
Thanks @p37307!

I do very much like the idea of backfilling bookmarks, and that should likely be quite straightforward to implement, too.

As I'm not a user of lists I find it hard to wrap my head around these.

Am I right in say that if people are on your list, then you'll always be following them too, or can people be on a list, without you following them?

The reason why I'm asking is, because, as far as I can see, Mastodon usually gets all replies to posts from accounts you follow without actually needing this script.

The only other problem I see is that we need to be careful not to backfill too much - otherwise we'll constantly encounter 429 rate limit errors, and the script just gets stuck ...

**Comment by nanos** [comment]
Fetching replies to bookmarked posts is now implemented since v4.1.1
